### PR TITLE
comment pull request

### PR DESCRIPTION
**Pull request by songWukong**
I've created this pull request for those of you who seriously intended to participate in the project, so now we are able to continue any discussions here

### CODE REVIEW

**Comment by Divya063** [comment]
Hey while running calc.py I'm getting this error 
```
Traceback (most recent call last):
  File "calc.py", line 110, in <module>
    result = calc.parse_Formula(source)
  File "calc.py", line 16, in parse_Formula
    result += self.__parse_Secondary__(expr)
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
```

**Comment by songWukong** [comment]
@Divya063, that's because currently in file "source.bas" we have "PRINT "hello world" ". In source.bas delete the line and insert any arithmetical expression like 3*(2+2)-6/3. Do not use spaces. I didn't yet implement any error handler yet, so that's why program crashed. Let me know if you were successful or not. That's very important for me. You can implement error handler as well if you want, it would be great actually. I'm now busy with implementing an entire MVC model, trying to gather all the classes together, I'll git push changes for about in an hour.

**Comment by songWukong** [comment]
@Divya063 and thank's for joining the project! Together we will build a beautiful and functional interpreter. Did you have a look at gui? Install python-tk if you don't already have it, by the way, what OS are you sitting on and where are you from?

**Comment by Divya063** [comment]
@songWukong I used an arithmetic expression and it is working fine. I'll look into the GUI and error handler as well. I'm having both Windows and Ubuntu on my system and I'm from India and thanks for giving me the opportunity to work on this. I was wondering maybe we can use slack for discussions.

**Comment by songWukong** [comment]
What is slack? and sorry, I got to go now, back in 4-5 hours

**Comment by songWukong** [comment]
And thank's for giving me a chance to learn how to code in a team! You're great)

**Comment by Divya063** [comment]
Slack is a team messaging service, I'll send you an invite :+1:

**Comment by songWukong** [comment]
@Divya063 great! Also please feel free to contact me via email rozovenkoe66@gmail.com you can send your code for discussions either.

**Pull request closed without merging**
